s = {
  {
    width = 495,
    height = 495,
    directory = "7x7-blurb",
    title = ZSTR("$$$/Layout/TemplateSizes/7x7=Small Square"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/7x7_metric=Small Square 18x18 cm"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/7x7=7 x 7 in (18 x 18 cm)"),
    imageWrap = true,
    softcover = true,
    dustJacket = true,
    defaultPaperType = "premium_lustre",
    id = "7x7-blurb"
  },
  {
    width = 585,
    height = 738,
    directory = "8x10_true-blurb",
    title = ZSTR("$$$/Layout/TemplateSizes/8x10_true=Standard Portrait"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/8x10_true_metric=Standard Portrait 20x25 cm"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/8x10_true=8 x 10 in (20 x 25 cm)"),
    doNotShowTitle = true,
    imageWrap = true,
    softcover = true,
    dustJacket = false,
    defaultPaperType = "standard_trade_matte",
    id = "8x10_true-blurb"
  },
  {
    width = 567,
    height = 720,
    directory = "8x10-blurb",
    title = ZSTR("$$$/Layout/TemplateSizes/8x10=Standard Portrait"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/8x10_metric=Standard Portrait 20x25 cm"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/8x10=8 x 10 in (20 x 25 cm)"),
    imageWrap = true,
    softcover = true,
    dustJacket = true,
    defaultPaperType = "premium_lustre",
    id = "8x10-blurb"
  },
  {
    width = 693,
    height = 594,
    directory = "10x8-blurb",
    title = ZSTR("$$$/Layout/TemplateSizes/10x8=Standard Landscape"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/10x8_metric=Standard Landscape 25x20 cm"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/10x8=10 x 8 in (25 x 20 cm)"),
    imageWrap = true,
    softcover = true,
    dustJacket = true,
    defaultPaperType = "premium_lustre",
    id = "10x8-blurb"
  },
  {
    width = 1152,
    height = 864,
    directory = "13x11-blurb",
    title = ZSTR("$$$/Layout/TemplateSizes/13x11=Wilson Large Landscape new 16x12"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/13x11_metric=Wilson Large Landscape 33x28 cm"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/13x11=13 x 11 in (33 x 28 cm)"),
    imageWrap = true,
    softcover = false,
    dustJacket = true,
    defaultPaperType = "premium_lustre",
    id = "13x11-blurb"
  },
  {
    width = 855,
    height = 864,
    directory = "12x12-blurb",
    title = ZSTR("$$$/Layout/TemplateSizes/12x12=Large Square"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/12x12_metric=Large Square 30x30 cm"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/12x12=12 x 12 in (30 x 30 cm)"),
    imageWrap = true,
    softcover = false,
    dustJacket = true,
    defaultPaperType = "premium_lustre",
    id = "12x12-blurb"
  },
  {
    width = 621,
    height = 810,
    directory = "8.5x11-blurb",
    title = ZSTR("$$$/Layout/TemplateSizes/8.5x11=Magazine Size"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/8.5x11_metric=Magazine Size 22x28 cm"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/8.5x11=8.5 x 11 in (22 x 28 cm)"),
    imageWrap = false,
    softcover = true,
    dustJacket = false,
    defaultPaperType = "premium_magazine",
    id = "8.5x11-blurb"
  },
  {
    width = 441,
    height = 666,
    directory = "6x9-blurb",
    title = ZSTR("$$$/Layout/TemplateSizes/6x9=Trade Book"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/6x9_metric=Trade Book 15x23 cm"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/6x9=6 x 9 in (15 x 23 cm)"),
    doNotShowTitle = true,
    imageWrap = true,
    softcover = true,
    dustJacket = true,
    defaultPaperType = "standard_trade_matte",
    id = "6x9-blurb"
  },
  {
    width = 369,
    height = 594,
    directory = "5x8-blurb",
    title = ZSTR("$$$/Layout/TemplateSizes/5x8=Pocket Trade Book"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/5x8_metric=Pocket Trade Book 13x20 cm"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/5x8=5 x 8 in (13 x 20 cm)"),
    doNotShowTitle = true,
    imageWrap = true,
    softcover = true,
    dustJacket = true,
    defaultPaperType = "standard_trade_matte",
    id = "5x8-blurb"
  },
  {
    width = 576,
    height = 324,
    directory = "16x9-folio",
    title = ZSTR("$$$/Layout/TemplateSizes/16x9=16:9 Screen"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/16x9_metric=16:9 Screen"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/16x9=16:9 Screen"),
    doNotTackOnSizeStr = true,
    imageWrap = false,
    softcover = false,
    dustJacket = false,
    defaultPaperType = "premium_lustre",
    id = "16x9-folio"
  },
  {
    width = 576,
    height = 432,
    directory = "4x3-folio",
    title = ZSTR("$$$/Layout/TemplateSizes/4x3=4:3 Screen (iPad)"),
    title_metric = ZSTR("$$$/Layout/TemplateSizes/4x3_metric=4:3 Screen (iPad)"),
    sizeStr = ZSTR("$$$/Layout/TemplateSizes/Dimensions/4x3=4:3 Screen (iPad)"),
    doNotTackOnSizeStr = true,
    imageWrap = false,
    softcover = false,
    dustJacket = false,
    defaultPaperType = "premium_lustre",
    id = "4x3-folio"
  }
}
